### ISSUE TITLE
SyntaxError: Non-ASCII character '\xc3' in file /home/tansell/foss/pybee/voc/tests/utils.py on line 628, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

### ISSUE THREAD

**Issue by mithro** [pybee/voc#231]
```
tansell@tansell-x1c-l:~/foss/pybee/voc$ python setup.py test
running test
running egg_info
creating voc.egg-info
writing voc.egg-info/PKG-INFO
writing top-level names to voc.egg-info/top_level.txt
writing dependency_links to voc.egg-info/dependency_links.txt
writing entry points to voc.egg-info/entry_points.txt
writing manifest file 'voc.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'Makefile'
warning: no files found matching 'requirements*.txt'
writing manifest file 'voc.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 44, in <module>
    test_suite='tests'
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 135, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 116, in with_project_on_sys_path
    func()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 160, in run_tests
    testLoader = cks
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 36, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 36, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/home/tansell/foss/pybee/voc/tests/structures/test_comparisons.py", line 1, in <module>
    from ..utils import TranspileTestCase
  File "/home/tansell/foss/pybee/voc/tests/utils.py", line 628
SyntaxError: Non-ASCII character '\xc3' in file /home/tansell/foss/pybee/voc/tests/utils.py on line 628, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

**Comment by freakboy3742** [comment]
This is caused by using Python 2 instead of Python 3. The README and the Getting Started Guide both indicate that Python 3.4 is required; but if you think this message needs additional reinforcement, please submit some suggested text as a PR.
