### ISSUE TITLE
AttributeError: 'module' object has no attribute 'test_codecs'

### ISSUE THREAD

**Issue by mithro** [pybee/voc#232]
```
tansell@tansell-x1c-l:~/foss/pybee/voc$ python3 setup.py test
running test
running egg_info
writing dependency_links to voc.egg-info/dependency_links.txt
writing top-level names to voc.egg-info/top_level.txt
writing entry points to voc.egg-info/entry_points.txt
writing voc.egg-info/PKG-INFO
reading manifest file 'voc.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'Makefile'
warning: no files found matching 'requirements*.txt'
writing manifest file 'voc.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 44, in <module>
    test_suite='tests'
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 135, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 116, in with_project_on_sys_path
    func()
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 160, in run_tests
    testLoader = cks
  File "/usr/lib/python3.4/unittest/main.py", line 92, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.4/unittest/main.py", line 139, in parseArgs
    self.createTests()
  File "/usr/lib/python3.4/unittest/main.py", line 146, in createTests
    self.module)
  File "/usr/lib/python3.4/unittest/loader.py", line 146, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.4/unittest/loader.py", line 146, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.4/unittest/loader.py", line 117, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 36, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.4/unittest/loader.py", line 114, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'test_codecs'
tansell@tansell-x1c-l:~/foss/pybee/voc$ python3 --version
Python 3.4.3
```

**Comment by mithro** [comment]
```
(venv) tansell@tansell-x1c-l:~/foss/pybee/voc$ ./venv/bin/py.test
============================================================================== test session starts ==============================================================================
platform linux -- Python 3.4.3, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/tansell/foss/pybee/voc, inifile: 
plugins: xdist-1.14
collected 10591 items / 1 errors 

requirements/tests.txt s
tests/test_utils.py ..................^C

==================================================================================== ERRORS =====================================================================================
_____________________________________________________________________ ERROR collecting tests/test_codecs.py _____________________________________________________________________
tests/test_codecs.py:2: in <module>
    from test.test_codecs import ReadTest
E   ImportError: No module named 'test.test_codecs'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
to show a full traceback on KeyboardInterrupt use --fulltrace
/usr/lib/python3.4/selectors.py:367: KeyboardInterrupt
================================================================= 18 passed, 1 skipped, 1 error in 5.84 seconds =================================================================
```

**Comment by mithro** [comment]
The solution seems to be in https://voc.readthedocs.io/en/latest/internals/contributing.html#setting-up-your-development-environment

**Comment by freakboy3742** [comment]
Closing on the basis that the contribution guide already covers this.
