### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by libertil** [pybee/voc#282]
I followed instruction on how to set up a dev environment.

When I run the tests  I get at the end of the procedure a number of errors due to missing files/directories. 
I am running on a Ubuntu 16.4 VM, Python 3.4.5,  javac 1.8.0_91 (openJDK) , ant  1.9.6 

Below a sample of the errors I get
======================================================================
ERROR: setUpClass (tests.structures.test_java.JavaTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/luca/voc-dev/voc/tests/utils.py", line 276, in setUpClass
    setUpSuite()
  File "/home/luca/voc-dev/voc/tests/utils.py", line 60, in setUpSuite
    out, err = proc.communicate(timeout=15)
  File "/usr/lib/python3.4/subprocess.py", line 959, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.4/subprocess.py", line 1621, in _communicate
    self._check_timeout(endtime, orig_timeout)
  File "/usr/lib/python3.4/subprocess.py", line 985, in _check_timeout
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command 'ant java' timed out after 15 seconds

----------------------------------------------------------------------
Ran 31 tests in 4771.214s

FAILED (errors=173)
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/luca/voc-dev/env/lib/python3.4/shutil.py", line 457, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/luca/voc-dev/voc/tests/tmpbf9imex0'

**Comment by freakboy3742** [comment]
This is quite odd - I can't say I've seen this before. 

Are you able to build the support library manually (i.e., running `ant java` at the command line by itself)?

**Comment by libertil** [comment]
Yes I am able to manually build the support library and run the "Hello world" sample program.

**Comment by freakboy3742** [comment]
It's a long shot, but it it possible there might be filesystem permission problems here? The test system will be trying to create temporary directories in the `tests` directory; if there are permission problems, this might be causing the errors.

Another possibility - how long does `ant java` take to run on you machine - if it's longer than 15 seconds, then that would explain the timeout.

**Comment by libertil** [comment]
I am inclined to rule out the permissions issue because other directories are successfully created in the tests directory. As for the timeout, ant java occasionally takes a long time to run on my VM. Is there a way to override the 15 sec timeout limit?

**Comment by libertil** [comment]
Yes I am able to build the library and to run the 'Hello world' sample program. 
 

    Il Venerdì 21 Ottobre 2016 2:56, Russell Keith-Magee <notifications@github.com> ha scritto:
 

 This is quite odd - I can't say I've seen this before. Are you able to build the support library manually (i.e., running ant java at the command line by itself)?—

**Comment by freakboy3742** [comment]
You say `ant java` "occasionally" takes a long time to run - can you narrow down why? It should be a fairly predictable and consistent build process, not something prone to prolonged delays. Is there something locking up or waiting for a network timeout?
