### ISSUE TITLE
Nesting list comprehensions causes crash at run time

### ISSUE THREAD

**Issue by eliasdorneles** [pybee/voc#368]
Using the following Python code in a **listcomp.py**:

```
matrix = [
    [x for x in range(3)]
    for i in range(3)
]
print(matrix)
```

The expected output (for CPython) is a 3x3 matrix like:

```
[[0, 1, 2], [0, 1, 2], [0, 1, 2]]
```

Running it with VOC though, I'm getting `IndexError: tuple index out of range`:

```
+ java -cp ../voc/dist/python-java-support.jar:. python.listcomp.__init__
Exception in thread "main" IndexError: tuple index out of range
	at org.python.types.Tuple.__getitem__(Tuple.java:334)
	at org.python.types.Function.populateAttrs(Function.java:41)
	at org.python.types.Function.<init>(Function.java:153)
	at python.listcomp.__init__.module$import(listcomp.py:2)
	at python.listcomp.__init__.main(listcomp.py)
```

**Comment by eliasdorneles** [comment]
Ugh, just realized this is essentially a duplicate of https://github.com/pybee/voc/issues/369
