### ISSUE TITLE
voc is not capable to cope with very long python scripts

### ISSUE THREAD

**Issue by leasunhy** [pybee/voc#406]
For benchmarking purpose (refs #363), I created a python script that has thousands of lines. The script looks like this (which can be run with CPython):

```python
class A:
    def __init__(self, val):
        self.val = val

    def __add__(self, other):
        return self.val + other.val

class B(A):
    def __init__(self, val):
        self.val = val

    def __radd__(self, other):
        return self.val + other.val + 1

def test():
    a = A(1)
    b = B(2)
    print(a + b)
    ##### `print(a + b)` repeats 2000 times
    print(a + b)

if __name__ == "__main__":
        test()
```

When compiling the script, voc throws:
```
Traceback (most recent call last):
  File "/home/leasunhy/voc/env/bin/voc", line 11, in <module>
    load_entry_point('voc', 'console_scripts', 'voc')()
  File "/home/leasunhy/voc/voc-github/voc/__main__.py", line 46, in main
    verbosity=args.verbosity
  File "/home/leasunhy/voc/voc-github/voc/transpiler.py", line 33, in transpile
    transpiler.write(outdir)
  File "/home/leasunhy/voc/voc-github/voc/transpiler.py", line 62, in write
    javaclassfile.write(out)
  File "/home/leasunhy/voc/voc-github/voc/java/klass.py", line 438, in write
    method.write(writer)
  File "/home/leasunhy/voc/voc-github/voc/java/methods.py", line 209, in write
    attribute.write(writer)
  File "/home/leasunhy/voc/voc-github/voc/java/attributes.py", line 48, in write
    self.write_info(writer)
  File "/home/leasunhy/voc/voc-github/voc/java/attributes.py", line 458, in write_info
    attribute.write(writer)
  File "/home/leasunhy/voc/voc-github/voc/java/attributes.py", line 48, in write
    self.write_info(writer)
  File "/home/leasunhy/voc/voc-github/voc/java/attributes.py", line 1840, in write_info
    writer.write_u2(start_pc)
  File "/home/leasunhy/voc/voc-github/voc/java/klass.py", line 73, in write_u2
    self._outfile.write(struct.pack('>H', u2))
struct.error: 'H' format requires 0 <= number <= 65535
```

After some playing with this, I noticed that this issue is not because the number of lines of the python script is too big, but because the generated Java bytecode is too long.

And this issue seems not being voc's fault, because when I use `javac` to compile a java file with a 10000-line main function, it says `code too large` as well (but a 8000-line main function will work).

This may hint that, focusing on performance, we should reduce the length of generated code as well.

**Comment by eliasdorneles** [comment]
Thanks for reporting, this was interesting! =)

I agree that this is not VOC's fault, [it seems that Java limits methods to 64K of bytecode](http://stackoverflow.com/questions/243097/javac-error-code-too-large), and therefore I'm closing this issue.

In practice, this shouldn't be a problem, and you can do a for-loop to write a benchmark.

**Comment by leasunhy** [comment]
@eliasdorneles Thank you for your review! ;-)
I know what you mean, but the issue in #363 is about "inlining selection logic between an operator and its reflected version", so the issue involves code length and a for-loop is not appropriate here.
Consider the case where we actually do the `+` for 100 different pairs of operands.
Yes, the issue is due to the 64K bytecode limit of Java, but we should be aware of this issue and accordingly make design decisions.
For example, in my incomplete benchmark, I found that if I inlined all the selection logic, it would be 200~300 bytes of code for only one `+` operator, whereas if I used a static method, a `+` operator would only cost about 50~60 bytes.

Yes, you're right ;-) The problem should not be raised in practice, and I note this down just for future reference (if any).
Thanks!

**Comment by freakboy3742** [comment]
I'm going to reopen this - not because we can fix the limitations of the Java VM, but because it's somewhere that we can report a much more helpful error. I've hit this one myself a couple of times, and it takes a few moments to remember what the likely cause is, and confirm that it is, in fact, what is going on.

@leasunhy's point is also a valid one in the context of #363 - we need to be careful about turning a "one line operation" like addition into a block of 5 opcodes, because it will rapidly shrink the maximum allowed code size. There are also lots of opportunities for optimisation in the existing code which we should investigate.

**Comment by Stewori** [comment]
Note that we used to have a similar issue with Jython. It hindered workability of a couple of frameworks, e.g. SymPy or PyOpenGL. We are now using CPython bytecode for such cases. It's not very efficient, but oversized functions are usually rare enough to let this work properly.
