### ISSUE TITLE
Fix keyword-only functions

### ISSUE THREAD

**Issue by eliasdorneles** [pybee/voc#432]
The following valid Python 3 code:

```
def func(*, a=1):
    print(a)

func(a=2)
func()
```

... gives the following output in CPython:

```
$ python functest.py 
2
1
```

... but raises NullPointerException if compiled and ran with VOC:

```
+ java -cp ../voc/dist/python-java-support.jar:. python.functest.__init__
2
Exception in thread "main" RuntimeError: java.lang.NullPointerException
	at org.python.types.Function.invoke(Function.java:412)
	at org.python.types.Function.invoke(Function.java:347)
	at python.functest.__init__.func(functest.py:2)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.types.Function.invoke(Function.java:388)
	at org.python.types.Function.invoke(Function.java:347)
	at python.functest.__init__.module$import(functest.py:5)
	at python.functest.__init__.main(functest.py)
```

**Comment by Ostrea** [comment]
I would like to work on it. Could you provide some hints on where to start?

**Comment by eliasdorneles** [comment]
@Ostrea Hey! I don't really know much more than what's in the above report at the moment.
The problem might be on the bytecode generated (in ast.py file) or in the code for calling functions (since it happens at runtime), it needs some debugging.

**Comment by Ostrea** [comment]
Thanks, will try to find problem

**Comment by gautamworah96** [comment]
Hello, I tried debugging this problem , This runtime error is caused by  `java.lang.reflect.InvocationTargetException e` on line no : 399 in the Function.java file
 ..this exception in turn occurs when there is an error in the function which is wrapped by invoke.
.Thus there appears to be a bug in the `adjustArguments(instance, args, kwargs)` method..I think the bug is in this code :` if (n_args == 0) {
            return null;
        }`
line: 262
Also to check whether the control is passing on to this function or no can we use `System.out.println()`
or do we have to use another method..
Kindly guide me ahead..or am I going in the wrong direction :(

**Comment by Ostrea** [comment]
According to my debugging the problem is on byte code level. Current implementation doesn't generate default args values for arguments with type `KEYWORD_ONLY`, thus we get `null` in `invoke`.

**Comment by Ostrea** [comment]
I have fixed this issue, but it has caused problems with varargs. Should I pull request changes and start new issue for varargs?

**Comment by eliasdorneles** [comment]
@Ostrea you should not create issues for problems, unless they're reproducible with the code from the official master branch.
You can still create a pull request so we can do an initial review, though.

**Comment by Ostrea** [comment]
Okay

**Comment by eliasdorneles** [comment]
Attempting to compile a function with one keyword-only argument is also failing:

```
def func(*, a):
    print(a)

func(a=2)
```

The above under CPython works, printing `2`, but attempting to compile it with VOC causes an error:

```
  File "/home/elias/src/voc-dev/voc/voc/python/ast.py", line 218, in visit_FunctionDef
    function = self._create_function(node, node.name, node.decorator_list)
  File "/home/elias/src/voc-dev/voc/voc/python/ast.py", line 975, in _create_function
    self.visit(node.args.kw_defaults[index])
  File "/home/elias/src/voc-dev/voc/voc/python/ast.py", line 165, in visit
    print('Node: %s' % dump(node))
  File "/home/elias/src/voc-dev/voc/voc/python/debug.py", line 45, in dump
    raise TypeError('expected AST, got %r' % node.__class__.__name__)
TypeError: expected AST, got 'NoneType'
```
