### ISSUE TITLE
Some bytes literals trigger issue in bytecode file writer

### ISSUE THREAD

**Issue by eliasdorneles** [pybee/voc#530]
Feeding the following code to VOC seems to trigger an issue in the code that writes the bytecode:

    b = b'\xc8'
    print(b)

Running with `voc -v` we get an error in the bytecode generation:

```
+ voc -v bytesliteraltest.py
Compiling bytesliteraltest.py ...
Writing ./python/bytesliteraltest.class ...
Traceback (most recent call last):
  File "/home/elias/.virtualenvs/voc/bin/voc", line 11, in <module>
    load_entry_point('voc', 'console_scripts', 'voc')()
  File "/home/elias/src/voc-dev/voc/voc/__main__.py", line 52, in main
    verbosity=args.verbosity
  File "/home/elias/src/voc-dev/voc/voc/transpiler.py", line 33, in transpile
    transpiler.write(outdir)
  File "/home/elias/src/voc-dev/voc/voc/transpiler.py", line 62, in write
    javaclassfile.write(out)
  File "/home/elias/src/voc-dev/voc/voc/java/klass.py", line 438, in write
    method.write(writer)
  File "/home/elias/src/voc-dev/voc/voc/java/methods.py", line 209, in write
    attribute.write(writer)
  File "/home/elias/src/voc-dev/voc/voc/java/attributes.py", line 48, in write
    self.write_info(writer)
  File "/home/elias/src/voc-dev/voc/voc/java/attributes.py", line 450, in write_info
    opcode.write(writer)
  File "/home/elias/src/voc-dev/voc/voc/java/opcodes.py", line 55, in write
    self.write_extra(writer)
  File "/home/elias/src/voc-dev/voc/voc/java/opcodes.py", line 470, in write_extra
    writer.write_s1(self.const)
  File "/home/elias/src/voc-dev/voc/voc/java/klass.py", line 64, in write_s1
    self._outfile.write(struct.pack('b', u1))
struct.error: byte format requires -128 <= number <= 127
```

I suspect that the code is assuming all bytes from input are signed bytes, but this needs further digging.

**Comment by freakboy3742** [comment]
Looks like an easy fix - `write_extra` is using `write_s1`, rather than `write_u1` - which is odd, because `read_extra` uses `read_u1`.

**Comment by eliasdorneles** [comment]
So I've just tried changing to `write_u1` but then the above code prints `b'\x-56'`, which seems to be result of reading signed, like:

```
>>> struct.unpack('b', b'\xc8')
(-56,)
```
