### ISSUE TITLE
We need better output for tests that raise exceptions

### ISSUE THREAD

**Issue by eliasdorneles** [pybee/voc#532]
Currently, when a test throws an error the output is way too confusing, no matter if you run with `py.test` or with `python setup.py test`.

I believe this is important enough to be fixed because it's hurting not only maintainer productivity (for example, I often find myself copying the test code into a temp file, just to be able to see a complete stacktrace) but it's also hard on project newcomers trying to make a test pass.

I added a test causing an exception to StrTests:

    def test_something(self):
        self.assertCodeExecution("""
            print(1 / 0)
            """)

Running it with `python setup.py test -s ...` gives me:

```
FAIL: test_something (tests.datatypes.test_str.StrTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elias/src/voc-dev/voc/tests/datatypes/test_str.py", line 24, in test_something
    """)
  File "/home/elias/src/voc-dev/voc/tests/utils.py", line 406, in assertCodeExecution
    self.assertEqual(java_out[substring_start:], END_OF_CODE_STRING_NEWLINE)
AssertionError: 'ero\n    test.py:1\n' != '===end of test===\n'
+ ===end of test===
- ero
-     test.py:1
```

Running with py.test, it gives:

```
================================================== FAILURES ===================================================
___________________________________________ StrTests.test_something ___________________________________________

self = <tests.datatypes.test_str.StrTests testMethod=test_something>

    def test_something(self):
        self.assertCodeExecution("""
                print(1 / 0)
>               """)

tests/datatypes/test_str.py:24: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/utils.py:406: in assertCodeExecution
    self.assertEqual(java_out[substring_start:], END_OF_CODE_STRING_NEWLINE)
E   AssertionError: 'ero\n    test.py:1\n' != '===end of test===\n'
E   + ===end of test===
E   - ero
E   -     test.py:1
==================================== 1 failed, 34 passed in 13.09 seconds =====================================
```

The pytest output is slightly better because it gives more context, but the assertion error message is still quite cryptic.

We should at least make the messages better, giving better hints of what's going on and how to fix it.

**Comment by captaincrunch21** [comment]
I want to grab this. Can You guide me

**Comment by eliasdorneles** [comment]
When i think about it, we could have better output for all test failures, not only the ones with exceptions.
I often find myself having to think hard to see which output is VOC's and which is CPython, in the case where no exception was thrown.
Instead of just a diff, we could have a message like:

```
For this code:

 ... code here

The expected output (with CPython 3.5.2) is:

... expected output here

But compiling with VOC and running with java -cp ... we got:

... output we got

The diff is:

... diff here
```
