### ISSUE TITLE
Attribute error when using += operator on an instance attribute

### ISSUE THREAD

**Issue by trbedwards** [pybee/voc#534]
Here's the minimum code (`voc_test.py`) that reproduces the issue:
```
class Thing(object):
    def __init__(self):
        self.a = 1

    def add_one(self):
        self.a += 1
```

When I do `voc -v voc_test.py` I get:
```
Traceback (most recent call last):
  File "/Users/tre11/anaconda2/envs/python3.5/lib/python3.5/site-packages/voc/python/ast.py", line 160, in visit
    super().visit(node)
  File "/Users/tre11/anaconda2/envs/python3.5/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/Users/tre11/anaconda2/envs/python3.5/lib/python3.5/site-packages/voc/python/ast.py", line 49, in dec
    fn(self, node)
  File "/Users/tre11/anaconda2/envs/python3.5/lib/python3.5/site-packages/voc/python/ast.py", line 341, in visit_AugAssign
    self.context.load_name(node.target.id)
AttributeError: 'Attribute' object has no attribute 'id'

Problem occurred in voc_test.py
Node: AugAssign(target=Attribute(value=Name(id='self', ctx=Load(), lineno=6, col_offset=8), attr='a', ctx=Store(), lineno=6, col_offset=8), op=Add(), value=Num(n=1, lineno=6, col_offset=18), lineno=6, col_offset=8)
```

This problem disappears when I replace `self.a += 1` with `self.a = self.a + 1`

**Comment by luizirber** [comment]
I worked on this issue in PR #544. On top of the `Attribute` case (this bug), I also considered the `Subscript` case that happens when accessing lists:
```python
a = [0, 1, 2]
a[0] += 1
```
