### ISSUE TITLE
del statement not implemented in voc

### ISSUE THREAD

**Issue by trbedwards** [pybee/voc#585]
I've create an example script `voc_test.py` like this:
```
x = 1
del x
```
but when I invoke `voc voc_test.py` I get this error:

```
Traceback (most recent call last):
  File "/Users/tre11/anaconda2/envs/python3.5/lib/python3.5/site-packages/voc/python/ast.py", line 160, in visit
    super().visit(node)
  File "/Users/tre11/anaconda2/envs/python3.5/lib/python3.5/ast.py", line 245, in visit
    return visitor(node)
  File "/Users/tre11/anaconda2/envs/python3.5/lib/python3.5/site-packages/voc/python/ast.py", line 49, in dec
    fn(self, node)
  File "/Users/tre11/anaconda2/envs/python3.5/lib/python3.5/site-packages/voc/python/ast.py", line 2145, in visit_Name
    raise NotImplementedError("Unknown context %s" % node.ctx)
NotImplementedError: Unknown context <_ast.Del object at 0x1057b8e10>

Problem occurred in voc_del.py
Node: Name(id='x', ctx=Del(), lineno=2, col_offset=4)
```

**Comment by eliasdorneles** [comment]
This should be fixed with the code in master.
Are you using the version installed from PyPI?

**Comment by trbedwards** [comment]
Ah, that would be why. It works when I install directly from github. Thanks!
