### ISSUE TITLE
Support long and double types in annotated methods

### ISSUE THREAD

**Issue by eliasdorneles** [pybee/voc#677]
Currently VOC doesn't generate correct bytecode for methods annotated with type `long`.

For this input:

```
class SomeClass:
    def somefunc(self, x: long):
        return x

print(SomeClass().somefunc(1))
```

When running with VOC, we get:

```
+ java -cp ../voc/dist/python-java-support.jar:. python.buglong
Exception in thread "main" java.lang.ClassFormatError: Arguments can't fit into locals in class file python/buglong/SomeClass
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at python.buglong.module$import(buglong.py:2)
	at python.buglong.main(buglong.py)
```

**Comment by eliasdorneles** [comment]
I dug this a bit deeper some time ago (I had help from Allison Kaptur which helped me a lot to understand), and tried to change [this part of the code](https://github.com/pybee/voc/commit/71ded21287f065ef8002d7e07ce18a4d68b447c7#diff-0e73d813f142357667b2d4eac7aed22eL236) to do what we thought would be the right thing.

I tried digging this further on my own but I'm stuck -- it's hard to write a test for this because `long` is not defined in Python.
