### ISSUE TITLE
Support for multiple generators in list comprehensions

### ISSUE THREAD

**Issue by eliasdorneles** [pybee/voc#684]
Currently, list comprehensions aren't supporting multiple generators.
For the following sample code:

    [str(i) for L in [[12, 3], [4, 5]] for i in L]

The expected output (CPython 3.5) is:

    ['12', '3', '4', '5']

Attempting to compile with VOC we get an error:

```
Traceback (most recent call last):
  File "/home/elias/src/voc-dev/voc/voc/python/ast.py", line 160, in visit
    super().visit(node)
  File "/home/elias/.pythonz/pythons/CPython-3.4.4/lib/python3.4/ast.py", line 245, in visit
    return visitor(node)
  File "/home/elias/src/voc-dev/voc/voc/python/ast.py", line 49, in dec
    fn(self, node, *args, **kwargs)
  File "/home/elias/src/voc-dev/voc/voc/python/ast.py", line 1207, in visit_ListComp
    raise NotImplementedError("Don't know how to handle multiple generators")
NotImplementedError: Don't know how to handle multiple generators

Problem occurred in _tempfile.py
Node: ListComp(elt=Name(id='i', ctx=Load(), lineno=2, col_offset=5), generators=[
    comprehension(target=Name(id='j', ctx=Store(), lineno=2, col_offset=11), iter=List(elts=[
        List(elts=[
            Num(n=12, lineno=2, col_offset=18),
            Num(n=3, lineno=2, col_offset=22),
          ], ctx=Load(), lineno=2, col_offset=17),
        List(elts=[
            Num(n=4, lineno=2, col_offset=27),
            Num(n=5, lineno=2, col_offset=30),
          ], ctx=Load(), lineno=2, col_offset=26),
      ], ctx=Load(), lineno=2, col_offset=16), ifs=[]),
    comprehension(target=Name(id='i', ctx=Store(), lineno=2, col_offset=38), iter=Name(id='j', ctx=Load(), lineno=2, col_offset=43), ifs=[]),
  ], lineno=2, col_offset=5)
```

**Comment by vaibhavsingh97** [comment]
@eliasdorneles Can i take up this issue?

**Comment by eliasdorneles** [comment]
@vaibhavsingh97 yes, that's what the up-for-grabs label is for -- feel free to send a PR :)

**Comment by swetanjal** [comment]
@eliasdorneles I would love to work on this issues. But I am a first time contributor, so you need to help me out on how to go about doing it. 

Let me know what to do next.

**Comment by MuLx10** [comment]
@eliasdorneles Can I take up the issue? Is it resolved?

**Comment by eliasdorneles** [comment]
So, this issue is not yet resolved (which is why it's still open), but it is a bit tricky for a first time contributor.

You'd need to get a bit familiar with the VOC internals, and learn [how to work with the code that generates Java bytecode](http://voc.readthedocs.io/en/latest/how-to/contribute.html#working-with-code-for-java-bytecode).

Other ways to get your feet wet with the bytecode stuff is to watch [the Pycon talk "How to write a Python transpiler" given by Russell](https://www.youtube.com/watch?v=9c4DEYIXYCM)), check out the source in [`voc/python/ast.py`](https://github.com/pybee/voc/blob/master/voc/python/ast.py) and look for the methods raising the error message shown in the stacktrace above.
