### ISSUE TITLE
Dex error on building for Android with briefcase

### ISSUE THREAD

**Issue by derEisele** [pybee/voc#708]
When I build an app for android with briefcase, I get the following error
```
    Caused by: java.lang.IllegalArgumentException: bad descriptor: Lpython/__phello__.foo;
        at com.android.dx.rop.type.Type.intern(Type.java:356)
        at com.android.dx.rop.type.Type.internClassName(Type.java:420)
        at com.android.dx.cf.cst.ConstantPoolParser.parse0(ConstantPoolParser.java:289)
        ... 27 more
    
1 error; aborting
:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
```
Voc version: 0.1.5

**Workaround:**
By @eliasdorneles
This uses the previous version of the Android Support package 
`python setup.py android --support-pkg https://pybee-briefcase-support.s3-us-west-2.amazonaws.com/Python-Android-support/3.5/Android/Python-3.5-Android-support.b5.tar.gz`

**Comment by freakboy3742** [comment]
It appears the b6 support build has some issues that didn't show up in testing. We've just deleted this support package; we'll push a new update soon.

**Comment by Huyston** [comment]
Maybe it is related to this:
`tests (and only in tests), it's acceptable to use method names with spaces enclosed in backticks. (Note that such method names are currently not supported by the Android runtime.) Underscores in method names are also allowed in test code`
From: https://stackoverflow.com/questions/46295418/cannot-use-kotlin-backticked-method-names-in-androidtest-bad-descriptor-except
