### ISSUE TITLE
Regression : generation expression inside class crashes

### ISSUE THREAD

**Issue by Dayof** [pybee/voc#717]
Error found on version 0.1.5 and master version. Works on 0.1.4.

```
class Test:
	def func(self):
		return any(x for x in range(5))

Test().func()
```

```
Exception in thread "main" RuntimeError: python.olar.Test.genexp_10f173860
	at org.python.types.Function.invoke(Function.java:412)
	at org.python.types.Function.invoke(Function.java:347)
	at python.olar.Test.func$py(olar.py:3)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.python.types.Function.invoke(Function.java:388)
	at org.python.types.Method.invoke(Method.java:47)
	at python.olar.module$import(olar.py:5)
	at python.olar.main(olar.py)
```

**Comment by TamsilAmani** [comment]
I'd like to work on this issue.
