### ISSUE TITLE
module 'voc.java.__main__' has no attribute 'main'

### ISSUE THREAD

**Issue by jedie** [pybee/voc#768]
Calling `vod --version` results in **ImportError: module 'voc.java.__main__' has no attribute 'main'**
```
$ voc --version
voc 0.1.5
$ python --version
Python 3.5.5
$ javac -version
javac 1.8.0_111-internal
$ vod --version
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2416, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'voc.java.__main__' has no attribute 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/vod", line 11, in <module>
    load_entry_point('voc', 'console_scripts', 'vod')()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2418, in resolve
    raise ImportError(str(exc))
ImportError: module 'voc.java.__main__' has no attribute 'main'
```

**Comment by freakboy3742** [comment]
Thanks for the report; we've neglected to add argparse handling to vod, so it's treating all arguments as class files. Should be an easy fix :-)

**Comment by zsilver1** [comment]
I'm working on a quick fix for this. I'm a first time contributor so I'm wondering what the description for the `vod` program should be in the argparser, and if there are any other arguments that need to be handled besides `version` and `-v`.

**Comment by freakboy3742** [comment]
@zsilver1 There's no additional arguments at the moment. `vod` is quick-and-dirty debugging tool; for the moment, the only arguments are `-v`, `--help` (which you get for free with argparse), and the class file to be decompiled.
