### ISSUE TITLE
import statement throws internal java.lang.ClassCastException

### ISSUE THREAD

**Issue by patiences** [pybee/voc#906]
```
from math import sqrt

sqrt(4)
```
throws this error: 

```
test (tests.datatypes.test_bool.BoolTests) ... java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at python.testdaemon.TestDaemon.main(TestDaemon.java:65)
Caused by: java.lang.ClassCastException: org.python.java.Module cannot be cast to org.python.Callable
	at python.test.module$import(test.py:3)
	at python.test.main(test.py)
	... 5 more

FAIL
```

**Comment by freakboy3742** [comment]
@VisibleMarkov Yes, VOC uses Java's internal libraries. That's not what is being reported here. The sample code provided by @patiences is legal Python; it should work when compiled by VOC.
